# Flight Delay prediction

In [1]:
import numpy as np
import pandas as pd
import torch
from torch import nn,optim
import datetime
from torch.utils import data
from random import sample,seed

## Importing Flight Data

In [2]:
flights = pd.read_csv("./data/flights.csv",low_memory=False)
airlines = pd.read_csv("./data/airlines.csv")
airports = pd.read_csv("./data/airports.csv")

## Preprocessing of the data

In [3]:
airports = {ch:i for i,ch in enumerate(flights.ORIGIN_AIRPORT.unique())}
airlines = {ch:i for i,ch in enumerate(airlines.IATA_CODE)}
airports['10666'] =len(airports)

In [4]:
# one hot encoder for day of the week
def one_hot_encode(size,val):
    a = np.zeros((size,),dtype=int)
    a[(val-1)] = 1
    return a

In [5]:
# Date and time preprocess copied from
# link - https://www.kaggle.com/fabiendaniel/predicting-flight-delays-tutorial/data
#_________________________________________________________
# Function that convert the 'HHMM' string to datetime.time
def format_heure(chaine):
    if pd.isnull(chaine):
        return np.nan
    else:
        if chaine == 2400: chaine = 0
        chaine = "{0:04d}".format(int(chaine))
        heure = datetime.time(int(chaine[0:2]), int(chaine[2:4]))
        return heure

In [6]:
flights['DATE'] = pd.to_datetime(flights[['YEAR','MONTH', 'DAY']])

In [7]:
# REFORMATING THE DATE VARIABLES
#__________________________________________________________________________________
flights['SCHEDULED_DEPARTURE'] = flights['SCHEDULED_DEPARTURE'].apply(format_heure) #create_flight_time(flights, 'SCHEDULED_DEPARTURE')
flights['DEPARTURE_TIME'] = flights['DEPARTURE_TIME'].apply(format_heure)
flights['SCHEDULED_ARRIVAL'] = flights['SCHEDULED_ARRIVAL'].apply(format_heure)
flights['ARRIVAL_TIME'] = flights['ARRIVAL_TIME'].apply(format_heure)
#__________________________________________________________________________
flights.loc[:5, ['SCHEDULED_DEPARTURE', 'SCHEDULED_ARRIVAL', 'DEPARTURE_TIME',
             'ARRIVAL_TIME', 'DEPARTURE_DELAY', 'ARRIVAL_DELAY']]

SCHEDULED_DEPARTURE SCHEDULED_ARRIVAL DEPARTURE_TIME ARRIVAL_TIME  \
0            00:05:00          04:30:00       23:54:00     04:08:00   
1            00:10:00          07:50:00       00:02:00     07:41:00   
2            00:20:00          08:06:00       00:18:00     08:11:00   
3            00:20:00          08:05:00       00:15:00     07:56:00   
4            00:25:00          03:20:00       00:24:00     02:59:00   
5            00:25:00          06:02:00       00:20:00     06:10:00   

   DEPARTURE_DELAY  ARRIVAL_DELAY  
0            -11.0          -22.0  
1             -8.0           -9.0  
2             -2.0            5.0  
3             -5.0           -9.0  
4             -1.0          -21.0  
5             -5.0            8.0

In [8]:
# DROPING IRRELEVANT COLUMNS
#_____________________________________________________________________________________
variables_to_remove = ['TAXI_OUT', 'TAXI_IN', 'WHEELS_ON', 'WHEELS_OFF', 'YEAR', 
                       'DAY','DATE', 'AIR_SYSTEM_DELAY',
                       'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY',
                       'WEATHER_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
                       'FLIGHT_NUMBER', 'TAIL_NUMBER', 'AIR_TIME']
flights.drop(variables_to_remove, axis = 1, inplace = True)
flights = flights[['AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
        'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY',
        'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY',
        'SCHEDULED_TIME', 'ELAPSED_TIME','MONTH','DAY_OF_WEEK']]
flights[:5]

AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT SCHEDULED_DEPARTURE  \
0      AS            ANC                 SEA            00:05:00   
1      AA            LAX                 PBI            00:10:00   
2      US            SFO                 CLT            00:20:00   
3      AA            LAX                 MIA            00:20:00   
4      AS            SEA                 ANC            00:25:00   

  DEPARTURE_TIME  DEPARTURE_DELAY SCHEDULED_ARRIVAL ARRIVAL_TIME  \
0       23:54:00            -11.0          04:30:00     04:08:00   
1       00:02:00             -8.0          07:50:00     07:41:00   
2       00:18:00             -2.0          08:06:00     08:11:00   
3       00:15:00             -5.0          08:05:00     07:56:00   
4       00:24:00             -1.0          03:20:00     02:59:00   

   ARRIVAL_DELAY  SCHEDULED_TIME  ELAPSED_TIME  MONTH  DAY_OF_WEEK  
0          -22.0           205.0         194.0      1            4  
1           -9.0           280.0         279.0      1            4  
2            5.0           286.0         293.0      1            4  
3           -9.0           285.0         281.0      1            4  
4          -21.0           235.0         215.0      1            4

In [9]:
# PROCESSING THE CATEGORICAL DATA
#___________________________________________________________________
flights['AIRLINE'] = flights['AIRLINE'].apply(lambda x: airlines[x])
flights['ORGIN_AIRPORT_V'] = flights['ORIGIN_AIRPORT'].apply(lambda x: airports[x])
flights['DESTINATION__AIRPORT_V'] = flights['DESTINATION_AIRPORT'].apply(lambda x: airports[x])
flights['DAY_OF_WEEK'] = flights['DAY_OF_WEEK'].apply(lambda x: one_hot_encode(7,x))
flights = flights[['AIRLINE','ORGIN_AIRPORT_V',"DESTINATION__AIRPORT_V",'ARRIVAL_DELAY','DAY_OF_WEEK','DEPARTURE_DELAY']]
flights.head()

AIRLINE  ORGIN_AIRPORT_V  DESTINATION__AIRPORT_V  ARRIVAL_DELAY  \
0        6                0                       3          -22.0   
1        1                1                      77           -9.0   
2        2                2                      97            5.0   
3        1                1                      84           -9.0   
4        6                3                       0          -21.0   

             DAY_OF_WEEK  DEPARTURE_DELAY  
0  [0, 0, 0, 1, 0, 0, 0]            -11.0  
1  [0, 0, 0, 1, 0, 0, 0]             -8.0  
2  [0, 0, 0, 1, 0, 0, 0]             -2.0  
3  [0, 0, 0, 1, 0, 0, 0]             -5.0  
4  [0, 0, 0, 1, 0, 0, 0]             -1.0

In [10]:
# CLEAN UP
#______________________________
flights.dropna(inplace =True)
flights = flights.reset_index()
flights = flights[['AIRLINE','ORGIN_AIRPORT_V',"DESTINATION__AIRPORT_V",'ARRIVAL_DELAY','DAY_OF_WEEK','DEPARTURE_DELAY']]
flights.head()

AIRLINE  ORGIN_AIRPORT_V  DESTINATION__AIRPORT_V  ARRIVAL_DELAY  \
0        6                0                       3          -22.0   
1        1                1                      77           -9.0   
2        2                2                      97            5.0   
3        1                1                      84           -9.0   
4        6                3                       0          -21.0   

             DAY_OF_WEEK  DEPARTURE_DELAY  
0  [0, 0, 0, 1, 0, 0, 0]            -11.0  
1  [0, 0, 0, 1, 0, 0, 0]             -8.0  
2  [0, 0, 0, 1, 0, 0, 0]             -2.0  
3  [0, 0, 0, 1, 0, 0, 0]             -5.0  
4  [0, 0, 0, 1, 0, 0, 0]             -1.0

In [11]:
# MAKING THE SEQUENCES OF INPUT DATA
#________________________________________________________________
spequence_length = 10000
output_length = 1
start = 0
data_batch = {}
decoder_input ={}
labels = {}
for i,x in enumerate(range(0,len(flights),spequence_length)):
#     print('id_{}:{}'.format(i,x))
#     y = x+spequence_length
    data_batch['id_{}'.format(i)] = [i for i in range(start,x)]
    air = flights.loc[x:x+output_length-1,'AIRLINE']
    f = flights.loc[x:x+output_length-1,'DEPARTURE_DELAY']
    decoder_input['id_{}'.format(i)] = air.to_list()
    labels['id_{}'.format(i)] = f.to_list()
    start = x

In [12]:
len(labels['id_0'])

1

In [13]:
decoder_input['id_0']

[6]

In [14]:
labels.keys()

dict_keys(['id_0', 'id_1', 'id_2', 'id_3', 'id_4', 'id_5', 'id_6', 'id_7', 'id_8', 'id_9', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14', 'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22', 'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30', 'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38', 'id_39', 'id_40', 'id_41', 'id_42', 'id_43', 'id_44', 'id_45', 'id_46', 'id_47', 'id_48', 'id_49', 'id_50', 'id_51', 'id_52', 'id_53', 'id_54', 'id_55', 'id_56', 'id_57', 'id_58', 'id_59', 'id_60', 'id_61', 'id_62', 'id_63', 'id_64', 'id_65', 'id_66', 'id_67', 'id_68', 'id_69', 'id_70', 'id_71', 'id_72', 'id_73', 'id_74', 'id_75', 'id_76', 'id_77', 'id_78', 'id_79', 'id_80', 'id_81', 'id_82', 'id_83', 'id_84', 'id_85', 'id_86', 'id_87', 'id_88', 'id_89', 'id_90', 'id_91', 'id_92', 'id_93', 'id_94', 'id_95', 'id_96', 'id_97', 'id_98', 'id_99', 'id_100', 'id_101', 'id_102', 'id_103', 'id_104', 'id_105', 'id_106', 'id_107', 'id_108', 'id_109',

In [15]:
labels['id_81']

[-5.0]

In [16]:
# DATA GENERATOR CLASS FOR EASY ACCESS AND PARALLELIZATION
#___________________________________________________________
class DataGen(data.Dataset):
    def __init__(self,list_id,labels):
        self.list_id = list_id
        self.labels = labels
    def __len__(self):
        return len(self.list_id)
    def __getitem__(self,index):
        ID = self.list_id[index]
        ind = data_batch[ID]
        X = flights.loc[ind,:'DAY_OF_WEEK']
        d_inp = torch.tensor(decoder_input[ID],dtype=torch.long)
        y = torch.tensor(labels[ID],dtype=torch.float)
        return d_inp,y,{'DAY_OF_WEEK':torch.tensor(X.DAY_OF_WEEK.to_list(),dtype=torch.float),
                  'AIRLINE': torch.tensor(X.AIRLINE.to_list(),dtype=torch.long),
                  'ORGIN_AIRPORT_V': torch.tensor(X.ORGIN_AIRPORT_V.to_list(),dtype=torch.long),
                  'DESTINATION__AIRPORT_V': torch.tensor(X.DESTINATION__AIRPORT_V.to_list(),dtype=torch.long)}

In [79]:
# PARAMETER FOR THE GENERATOR
#_____________________________
params = {'batch_size': 8,
          'shuffle': False,
          'num_workers': 0}

In [80]:
# SPLITING UP THE DATA INTO TRAINING AND VALIDATION
#_____________________________________________________
seed(1234)
length = int(len(data_batch.keys())*0.75)
training_ids = sample(list(data_batch.keys()),length)
validation_ids = []
for i in list(data_batch.keys()):
    if i not in training_ids:
        validation_ids.append(i)

In [81]:
#CREATING DATALOADERS
#_______________________________________________________________
training_set = DataGen(training_ids, labels)
training_generator = data.DataLoader(training_set, **params)
validation_set = DataGen(validation_ids, labels)
validation_generator = data.DataLoader(validation_set, **params)

In [82]:
d_inp,y,x = next(iter(training_generator))# training_set.__getitem__(0)

In [83]:
y.shape

torch.Size([8, 1])

In [84]:
d_inp.shape

torch.Size([8, 1])

In [85]:
d_inp

tensor([[ 6],
        [ 8],
        [12],
        [ 9],
        [ 5],
        [ 0],
        [ 5],
        [ 1]])

In [86]:
embeds = nn.Embedding(len(airlines),4)

In [87]:
embeds(x['AIRLINE']).shape

torch.Size([8, 10000, 4])

# MODEL DEFINITION

In [88]:
cuda = False #torch.cuda.is_available()

In [89]:
# MODEL DEFINITION
#_________________
class model(nn.Module):
    
    def __init__(self,airline_embed_size=4,airport_embed_size=300,hidden_size=83,no_of_layers=2,dropout=0.25,linear_size=512):
        super(model,self).__init__()
        
        # DEFINING THE VARIABLES AND PARAMETERS
        self.airline_embed_size = airline_embed_size
        self.airport_embed_size = airport_embed_size
        self.hidden_size = hidden_size
        self.no_of_layers =no_of_layers
        
        # MODEL ELEMENTS
        self.airline_embed = nn.Embedding(len(airlines),airline_embed_size)
        self.airport_embed = nn.Embedding(len(airports),airport_embed_size) 
        self.conv1 = nn.Conv1d(10000,1024,kernel_size=1)
        self.conv2 = nn.Conv1d(1024,1024,kernel_size=2,stride=2,padding=1)
        self.conv3 = nn.Conv1d(1024,1024,kernel_size=2,stride=2,padding=1)
        self.conv4 = nn.Conv1d(1024,2048,1)
        self.conv5 = nn.Conv1d(2048,1,1)
        # HIDDEN SIZE IS CALCULATED BASED ON DOWN SIZING THROUGH CONVOLUTION
        self.linear_1 = nn.Linear(hidden_size,linear_size)
        self.linear_2 = nn.Linear(linear_size,linear_size)
        self.out = nn.Linear(linear_size,1)
        self.drop = nn.Dropout(p=dropout)
        
    def forward(self,x,decode):
        input_ =torch.cat((x['DAY_OF_WEEK'],self.airline_embed(x['AIRLINE']),(self.airport_embed(x['DESTINATION__AIRPORT_V'])-self.airport_embed(x['ORGIN_AIRPORT_V']))),2)
        # CONCATINATED DAY OF THE WEEK, DELAY, AIRLINE AND DESTINATION-ORIGIN(GRAPH REP)
        if cuda:
            input_ = input_.cuda()
            decode = decode.cuda()
        
        decode = self.airline_embed(decode)
        
        out = self.conv1(input_)
        out = self.conv2(out)
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.conv5(out)
        out = out.view(params['batch_size'],-1)
        decode = decode.view(params['batch_size'],-1)
        out = torch.cat((out,decode),1)
        out = self.drop(self.linear_1(out))
        out = self.drop(self.linear_2(out))
        out = self.out(out)
        
        return out
    

In [90]:
#LOSS AND OPTIMISATION FUNCTIONS
conv = model()
criterian = nn.MSELoss()
optimizer = optim.SGD(conv.parameters(),lr =0.001)

# Training

In [91]:
epoch = 5
if cuda:
    conv.cuda()

for e in range(0,epoch):
    running_loss =0
    conv.train()
    count =0
    for decode,y,x in training_generator:
        if cuda:
            y = y.cuda()
#         print(decode.shape)
        out = conv(x,decode)
        loss = criterian(out,y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        running_loss +=loss.item()
        print('epoch {}: count {} loss={}'.format(e,count,loss))
        count =count+1
    else:
        print(f'The Training loss = {running_loss/count}')


epoch 0: count 0 loss=210.97486877441406
epoch 0: count 1 loss=3984.412353515625
epoch 0: count 2 loss=5241.59228515625
epoch 0: count 3 loss=288.71710205078125
epoch 0: count 4 loss=837.2205200195312
epoch 0: count 5 loss=1603.9755859375
epoch 0: count 6 loss=499.2698059082031
epoch 0: count 7 loss=114.96786499023438
epoch 0: count 8 loss=239.58566284179688
epoch 0: count 9 loss=357.3929443359375
epoch 0: count 10 loss=37.96697998046875
epoch 0: count 11 loss=1334.9111328125
epoch 0: count 12 loss=98.46881103515625
epoch 0: count 13 loss=628.2657470703125
epoch 0: count 14 loss=69.04366302490234
epoch 0: count 15 loss=124.50617980957031
epoch 0: count 16 loss=55.07107925415039
epoch 0: count 17 loss=1014.5302124023438
epoch 0: count 18 loss=1737.5887451171875
epoch 0: count 19 loss=269.7950439453125
epoch 0: count 20 loss=73.91303253173828
epoch 0: count 21 loss=38.276893615722656
epoch 0: count 22 loss=2739.23193359375
epoch 0: count 23 loss=2681.8349609375


RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 2 at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensor.cpp:603

In [44]:
for i in range(2):
    d,y,x = next(iter(training_generator))

In [45]:
x

{'DAY_OF_WEEK': tensor([[[0., 1., 0.,  ..., 0., 0., 0.],
          [0., 1., 0.,  ..., 0., 0., 0.],
          [0., 1., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 1.,  ..., 0., 0., 0.],
          [0., 0., 1.,  ..., 0., 0., 0.],
          [0., 0., 1.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 1., 0., 0.],
          [0., 0., 0.,  ..., 1., 0., 0.],
          [0., 0., 0.,  ..., 1., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 1.],
          [0., 0., 0.,  ..., 0., 0., 1.],
          [0., 0., 0.,  ..., 0., 0., 1.],
          ...,
          [1., 0., 0.,  ..., 0., 0., 0.],
          [1., 0., 0.,  ..., 0., 0., 0.],
          [1., 0., 0.,  ..., 0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0.,  ..., 1., 0., 0.],
          [0., 0., 0.,  ..., 1., 0., 0.],
          [0., 0., 0.,  ..., 1., 0., 0.],
          ...,
          [0., 0.,

In [48]:
d.shape

torch.Size([32, 1])

In [49]:
y.shape

torch.Size([32, 1])

In [52]:
for i,d in enumerate(training_generator):
    print(i)
    print(d)

0
[tensor([[ 6],
        [ 8],
        [12],
        [ 9],
        [ 5],
        [ 0],
        [ 5],
        [ 1],
        [ 1],
        [ 0],
        [ 1],
        [10],
        [ 0],
        [ 1],
        [12],
        [ 5],
        [ 1],
        [ 1],
        [ 5],
        [ 7],
        [ 5],
        [ 1],
        [ 5],
        [10],
        [ 8],
        [ 8],
        [ 8],
        [ 0],
        [ 0],
        [ 9],
        [ 6],
        [ 8]]), tensor([[  4.],
        [ -7.],
        [ -1.],
        [ 39.],
        [ -3.],
        [  8.],
        [ -4.],
        [ -3.],
        [ -3.],
        [169.],
        [ -5.],
        [  3.],
        [ -2.],
        [ -5.],
        [ -3.],
        [ 57.],
        [204.],
        [ -3.],
        [ -7.],
        [  5.],
        [  9.],
        [ -2.],
        [ -7.],
        [ 17.],
        [ -3.],
        [ 41.],
        [ -5.],
        [ -4.],
        [ 25.],
        [ -4.],
        [  1.],
        [ -1.]]), {'DAY_OF_WEEK': tensor([[[0., 1.,

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/sachin/anaconda3/envs/deep/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 2 at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensor.cpp:603


In [92]:
len(training_generator)

54

In [93]:
training_set.__getitem__(23)

(tensor([10]),
 tensor([17.]),
 {'DAY_OF_WEEK': tensor([[0., 0., 0.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 1.],
          [0., 0., 0.,  ..., 0., 0., 1.],
          [0., 0., 0.,  ..., 0., 0., 1.]]),
  'AIRLINE': tensor([ 8,  8,  8,  ..., 12, 12,  7]),
  'ORGIN_AIRPORT_V': tensor([ 67, 110, 110,  ...,  16,  25,  67]),
  'DESTINATION__AIRPORT_V': tensor([ 39,  46,  86,  ...,  59,  94, 122])})

In [94]:
training_set.__getitem__(23)

(tensor([10]),
 tensor([17.]),
 {'DAY_OF_WEEK': tensor([[0., 0., 0.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.],
          [0., 0., 0.,  ..., 0., 1., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 1.],
          [0., 0., 0.,  ..., 0., 0., 1.],
          [0., 0., 0.,  ..., 0., 0., 1.]]),
  'AIRLINE': tensor([ 8,  8,  8,  ..., 12, 12,  7]),
  'ORGIN_AIRPORT_V': tensor([ 67, 110, 110,  ...,  16,  25,  67]),
  'DESTINATION__AIRPORT_V': tensor([ 39,  46,  86,  ...,  59,  94, 122])})